### ISSUE TITLE
Stuck at “Collecting Drives Names”

### ISSUE THREAD

**Issue by Abdullah-Albanna** [EmuDeck/emudeck-we#28]
I’ve downloaded it from the official script that I got from the website, everything is installed with no errors, but it gets stuck at the part where I select the disk that I want to install it on!
![62120E84-F223-4C6A-BC48-A46B7C155DBD](https://github.com/EmuDeck/emudeck-we/assets/115571443/d3d2e33d-6124-49dc-b5bb-87b927037430)

**Comment by dragoonDorise** [comment]
@Abdullah-Albanna should be fixed, please try again

**Comment by Abdullah-Albanna** [comment]
@dragoonDorise Nothing really changed, still gets stuck in their.

I should note that my hard drive contains a Mac (apfs)(dual booting with mac) partition, so maybe it’s the reason ?!
![C72E3A41-7319-4222-A1BC-9E5941408FD4](https://github.com/EmuDeck/emudeck-we/assets/115571443/2670e817-3af8-484a-b990-5a0d3ce50ec9)

I use APFS for Windows by Paragon Software to mount my Mac partition, I also tried without

**Comment by sonofmartinus** [comment]
Same issue here.

**Comment by Abdullah-Alternative** [comment]
@sonofmartinus 
Yeah, and it still does not work to this day, let me know if you found a solution

**Comment by sonofmartinus** [comment]
@Abdullah-Albanna in my case I had  PowerShell profiles in the WindowsPowershell (PowerShell 5.1) and PowerShell (PowerShell 7) directories. Once I removed the profiles, which had some customization that I had added to load when I loaded my PowerShell console, then EmuDeck was able to find drives without any issues. 

Let me know if this makes sense.

**Comment by darksuika** [comment]
@sonofmartinus I'm a little lost on your solution. Could you go into a bit more depth of how to look for these profiles and remove them? 

Thanks in advance :)

**Comment by sonofmartinus** [comment]
@darksuika 

Depending on which OS you have, you may have two PowerShell folders within your computer's documents folder as shown below. 
![explorer_TyDORJe4w7](https://github.com/EmuDeck/emudeck-we/assets/152257537/e9431972-89fa-4166-8648-bf2b635b36cc)


WindowsPowerShell is for PowerShell 5.1 which comes with Windows 11 out of the box, the one folder named PowerShell is for PowerShell versions 6 and later. You could have 1 or both, regardless you will delete the powershell profile from any of those folder if they are present in your computer. 


![explorer_yXuij482Jt](https://github.com/EmuDeck/emudeck-we/assets/152257537/c5075373-8400-4891-969d-b22d55821b8e)
![explorer_S4zGn5f8vW](https://github.com/EmuDeck/emudeck-we/assets/152257537/a8998b2c-58fd-40a0-90bd-320e0c2eacba)

P.D. This is what ultimately worked for me, but keep in mind this was my specific case and I am unsure if this works for other people having the same issue with drives never populating. Let me know if this makes sense.

**Comment by omcsilva** [comment]
> @darksuika
> 
> Depending on which OS you have, you may have two PowerShell folders within your computer's documents folder as shown below. ![explorer_TyDORJe4w7](https://private-user-images.githubusercontent.com/152257537/302146886-e9431972-89fa-4166-8648-bf2b635b36cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTk2NDIsIm5iZiI6MTcyNzA1OTM0MiwicGF0aCI6Ii8xNTIyNTc1MzcvMzAyMTQ2ODg2LWU5NDMxOTcyLTg5ZmEtNDE2Ni04NjQ4LWJmMmI2MzViMzZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjQyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTc3ZDQwNjY4NzZmZjc4YjEzZmI3OTg4ZjIxZWNjNDkzZDU2OGU4NzAzOGEyM2YxZjM2Zjg2YWVjNTFlZWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LYBxel1JJWfh4_Gu9BK-qHqvSw_G5EJ5PRMk37OJlKQ)
> 
> WindowsPowerShell is for PowerShell 5.1 which comes with Windows 11 out of the box, the one folder named PowerShell is for PowerShell versions 6 and later. You could have 1 or both, regardless you will delete the powershell profile from any of those folder if they are present in your computer.
> 
> ![explorer_yXuij482Jt](https://private-user-images.githubusercontent.com/152257537/302147071-c5075373-8400-4891-969d-b22d55821b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTk2NDIsIm5iZiI6MTcyNzA1OTM0MiwicGF0aCI6Ii8xNTIyNTc1MzcvMzAyMTQ3MDcxLWM1MDc1MzczLTg0MDAtNDg5MS05NjlkLWIyMmQ1NTgyMWI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjQyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzMwZDViNTQyYzM3ZTA3ZTQ3OGYyZGE3MDE4ZGRhNTFiZmFhZDRiYzRkMWMzOTJjNTFjMjg2ZGQxOGM0MGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HgjC6d94EBdQ2-CKu_TguStCMkCeyqTHN17uyWGYrhc) ![explorer_S4zGn5f8vW](https://private-user-images.githubusercontent.com/152257537/302147078-a8998b2c-58fd-40a0-90bd-320e0c2eacba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTk2NDIsIm5iZiI6MTcyNzA1OTM0MiwicGF0aCI6Ii8xNTIyNTc1MzcvMzAyMTQ3MDc4LWE4OTk4YjJjLTU4ZmQtNDBhMC05MGJkLTMyMGUwYzJlYWNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMjQyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjIwMDQzZWZmNWQ1YTJlMjJiY2MwNDcxNDkzNWVjZDgyOTBlMDZmMDBhNmNkMjk1YjFlN2NkMWQzMGRhYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hd4Y9QRpOAITfUZ7vWS4NbOjHoH9MJp80g2enzSfMAA)
> 
> P.D. This is what ultimately worked for me, but keep in mind this was my specific case and I am unsure if this works for other people having the same issue with drives never populating. Let me know if this makes sense.

Thats exactly what I needed.  After trying multiple solutions, deleting profile.ps1 solved the problem for me.  Thank you!

**Comment by Abdullah-Albanna** [comment]
@sonofmartinus 

Very late reply, sorry 


But no, I don't have any PowerShell profiles 

It's empty
